# Generated by Django 3.2.5 on 2021-07-25 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Haemoglobin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_presure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sugar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verfied',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
